[tool.poetry]
name = "hw1"
version = "0.1.0"
description = ""
authors = ["werwty <bizhang@redhat.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "^1.0.0"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
